#include "../../../include/view/components/BoardSquare.hpp"

BoardSquare::BoardSquare(const sf::Vector2f &pos, const sf::Vector2f &size, const std::string &squareName, int id,
const sf::Color bg):UIComponent(pos, size),background_color(bg), square_id(id) {
    initText();
    initBoardSide();
    background.setPosition(pos);
    background.setSize(size);
    background.setFillColor(background_color);
    background.setOutlineThickness(1.0f);
    background.setOutlineColor(sf::Color::Black);
}

bool BoardSquare::isCornerSquare() {
    return board_side == BoardSide::BottomLeft ||
           board_side == BoardSide::BottomRight ||
           board_side == BoardSide::TopLeft ||
           board_side == BoardSide::TopRight;
}

void BoardSquare::setBoardSide(const BoardSide side) {
    board_side = side;
}

void BoardSquare::initBoardSide() { //TODO
    setBoardSide(BoardSide::TopLeft);
}

void BoardSquare::initText() {
    if (!font.loadFromFile("../../assets/arial.ttf")) {
        throw std::runtime_error("Failed to load font from ../../assets/arial.ttf");
    }
    text.setFont(font);
    text.setCharacterSize(12);
    text.setFillColor(sf::Color::Black);
    //set text rotation:
    setTextRotation();
    //set text position:
    setTextPosition();
}

void BoardSquare::setTextRotation() {
    switch (board_side) {
        case BoardSide::Bottom:
            text.setRotation(0);
        break;
        case BoardSide::Left:
            text.setRotation(90);
        break;
        case BoardSide::Top:
            text.setRotation(180);
        break;
        case BoardSide::Right:
            text.setRotation(270);
        break;
        case BoardSide::BottomLeft:
            text.setRotation(45);
        break;
        case BoardSide::BottomRight:
            text.setRotation(315);
        break;
        case BoardSide::TopLeft:
            text.setRotation(135);
        break;
        case BoardSide::TopRight:
            text.setRotation(225);
        break;
    }
}

void BoardSquare::setTextPosition() {
    //TODO, generated by claude
    // Get text bounds for centering
    sf::FloatRect textBounds = text.getLocalBounds();

    if (isCornerSquare()) {
        // For corner squares, position text diagonally
        float centerX = position.x + CORNER_SIZE / 2;
        float centerY = position.y + CORNER_SIZE / 2;

        // Adjust based on which corner
        switch (board_side) {
            case BoardSide::BottomLeft:
                text.setPosition(centerX - textBounds.width / 2, centerY);
                break;
            case BoardSide::BottomRight:
                text.setPosition(centerX + textBounds.width / 2, centerY);
                break;
            case BoardSide::TopLeft:
                text.setPosition(centerX - textBounds.width / 2, centerY - textBounds.height);
                break;
            case BoardSide::TopRight:
                text.setPosition(centerX + textBounds.width / 2, centerY - textBounds.height);
                break;
        }
    } else {
        // For regular squares, center text based on side
        switch (board_side) {
            case BoardSide::Bottom:
                text.setPosition(
                    position.x + (size.x - textBounds.width) / 2,
                    position.y + TEXT_PADDING
                );
                break;
            case BoardSide::Top:
                text.setPosition(
                    position.x + (size.x + textBounds.width) / 2,
                    position.y + size.y - TEXT_PADDING
                );
                break;
            case BoardSide::Left:
            case BoardSide::Right:
                text.setPosition(
                    position.x + TEXT_PADDING,
                    position.y + (size.y + textBounds.width) / 2
                );
                break;
        }
    }
}


